version: "3.8"
services:
  postgres_narayana:
    container_name: postgres_narayana
    image: postgres:12.2
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
    ports:
      - "5432:5432"
      
  jaeger_ifood:
    container_name: jaeger_narayana
    image: jaegertracing/all-in-one:1.17
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"